name: Zhang Hao Yang
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: war
        run: |
         chmod 777 ./*
         bash mission.sh
         
